### PR TITLE
Add resubmit gateway

### PR DESCRIPTION
**Pull request by derek63**

### CODE REVIEW

**Comment by derek63** [comment]
@alechenninger Ready for your review whenever you have the time

**Comment by alechenninger** [comment]
Few minor things:
- I would probably change is to put resync specific stuff in common-gateway in the resync module and resubmit stuff in the resubmit module (the request / response objects, basically). Is there a reason they are in common?
- This was already there previously, but in `toJson` on the `GatewayRequest`, you can move the `ObjectMapper` to a static field. It is fully thread-safe, so we don't need to create a new one each call, which apparently is expensive. For more info: http://wiki.fasterxml.com/JacksonBestPracticesPerformance

I'm not sure crazy about the inheritance hierarchy there with the requests, but, it's simple enough. The whole thing is pretty simple honestly so, I don't think it poses much of a concern at the moment.

Thanks!

**Comment by derek63** [comment]
I put the resync and resubmit requests and response in common so clients of the services could pull those in as dependencies and not have to fiddle with manually creating JSON or worrying about filtering out Spring MVC classes to pull things in.  This also allows us to not have to maintain a separate client library or API jar.  The exceptions went along for the ride so there weren't weird circular dependencies.

`GatewayRequest` has been updated to use a static `ObjectMapper` per the recommendations

Can you elaborate on the "I'm not sure crazy about the inheritance hierarchy there with the requests"

**Comment by alechenninger** [comment]
Makes sense!

As far as not being "super\* crazy" about the inheritance, I'm generally just not very much a fan of inheritance as a means of code-reuse. Maybe it would be better to instead have a 'status' class that has a status enum and a message with it, and then both requests use that with no base class. Of course, then you don't get the toJson and toXML methods, although I feel those are maybe a little unorthodox too where usually the serialization concerns are addressed outside of the model class itself. At the same time I don't think it's a very huge deal right now, so, unless you are inspired to change it, I'm fine with merging as is :). After all, some of that was already in place earlier, and so even if we wanted to change it, that change would probably be out of scope of this PR.

**Pull request merged**
